CREATE TABLE dentist (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    cro VARCHAR(50),
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_DENTIST'
);